---
title: "R Notebook"
output: github_domcument
---


```{r}
###Carrega os dados
df_class <- fread("/dados/gustavo_cruz/novo/classification_train.csv",
                  sep = ",", dec = ".")

df_class_test <- fread("/dados/gustavo_cruz/novo/classification_test.csv",
                       sep = ",", dec = ".")
###Função skim verifica a disposição dos dados e todas as suas caracteristicas
df_class %>% skim
```


```{r}
##3tabela de correlações --- é possível verificar que x1 tem correlação positiva em 
##relação à variavel target, assim como x2 tem correlação negativa
##isso terá impacto na decisao do modelo de classificação
cor(df_class)
```

```{r}
##verificando se os dados estão desbalanceados via tabela de frequencias
table(df_class$target)
```
```{r}
##Aplicando um modelo de regressão logistica, considerando a natureza da variavel target,
## e também por ser um modelo com boa performance para datasets com baixo
##número de linhas e de colunas
model_class <- glm(target ~ x1+x2, df_class, family = "binomial")
##resumo
summary(model_class)
```
```{r}
##Matriz de confusão
matriz_confusao <- confusionMatrix(table(predict(model_class, type = "response") >= 0.5,
                      df_class$target == 1)[2:1, 2:1])
##Precisão
precision <- matriz_confusao[["byClass"]][["Precision"]]
##Recall
recall <- matriz_confusao[["byClass"]][["Recall"]]
##F1 score
F1 <- matriz_confusao[["byClass"]][["F1"]]


print(matriz_confusao)
print(paste("Precisão:", precision))
print(paste("Recall:", recall))
print(paste("F1:", F1))
```

```{r}
###Gráfico da curva Roc e sua respectiva área embaixo da curva
##92,2% é um excelente valor, mostrando a alta capacidade de predição do modelo
ROC <- roc(response = df_class$target, 
           predictor = model_class$fitted.values)

ggplotly(
  ggroc(ROC, color = "#440154FF", size = 1) +
    geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1),
                 color="grey40",
                 size = 0.2) +
    labs(x = "Especificidade",
         y = "Sensitividade",
         title = paste("Área abaixo da curva:",
                       round(ROC$auc, 3),
                       "|",
                       "Coeficiente de Gini",
                       round((ROC$auc[1] - 0.5) / 0.5, 3))) +
    theme_bw()
)

```
```{r}
##Gráfico de impacto das variaveis explicativas
model_class %>%
  tidy() %>% 
  filter(term != "(Intercept)") %>%
  ggplot(aes(estimate, fct_reorder(term, estimate))) +
  geom_vline(xintercept = 0, color = "gray50", lty = 2, size = 1.2) +
  geom_errorbar(aes(
    xmin = estimate - std.error,
    xmax = estimate + std.error
  ),
  width = .2, color = "gray50", alpha = 0.7
  ) +
  geom_point(size = 2, color = "#85144B") +
  labs(y = NULL, x = "Variáveis Explicativas")

```
```{r}
##Fazendo a predição no conjunto de teste
predicao <- cbind(df_class_test,
                  predict(model_class, df_class_test, type = "response")) %>% 
  rename(predict = V2)
predicao$predict <- ifelse(predicao$predict >= 0.5,1,0)

##Matriz de confusão d conjunto de teste
confusionMatrix(table(predicao$target,predicao$predict))

```

